### ISSUE TITLE
User can see their car and the map

### ISSUE THREAD

**Issue by BrianBozi** [BrianBozi/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

![image](https://user-images.githubusercontent.com/70422100/120697694-e4d5fb80-c462-11eb-81e0-3c69d23ff95f.png)

- [x] Create html, css, js files
- [x] Put the title "Driving Game" in the HTML head.
- [x] Insert the favicon to the head of the HTML document. 
- [x] Create a div with the class of container. 
- [x] Create div with the class of '.car-container'.
- [x] Add the car image onto the  '.car-container' div.
- [x] In the css stylessheet,   set the background-color of the HTML boday to green. 
- [x] Ensure that the car is a resoanble size if not already.
- [x] Ensure that the  car is on the top left for the start
