### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by BrianBozi** [BrianBozi/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

![image](https://user-images.githubusercontent.com/70422100/120698239-a12fc180-c463-11eb-9b75-5f3ae534e2fd.png)
## ✅ Task List

- [x] Query Select the img of the car.
- [x] Add an event listener of key down on the document. 
- [ ] Within the event Listener, have is so that once the key is pressed, the car will rotate to that direction. 
- [ ] Repeat for the all directions.
- [ ] Ensure that each key  has the correct corresponding "direction"
- [ ] Use CSS styles to smooth the direction change.
