### ISSUE TITLE
User can start there car

### ISSUE THREAD

**Issue by BrianBozi** [BrianBozi/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

![image](https://user-images.githubusercontent.com/70422100/120698934-91fd4380-c464-11eb-8723-90f9f1ecb37c.png)

## ✅ Task List

- [ ] add location to data model to hold the car's x and y coordinates
- [ ] use absolute positioning for the car image
- [ ] Use the style property of element objects to change your car's top and left box offset styles
https://www.w3schools.com/jsref/prop_html_style.asp might be of help

- [ ] set car movement to 16 milliseconds for a smooth ride. 
- [ ] have the car go from the left side of the page to the right side.
